head.js( app_contextPath + "/includes/jmesa/jquery-1.9.1.min.js",
         app_contextPath + "/js/lib/jquery.tmpl.js",
         app_contextPath + "/js/lib/underscore-min.js",           
         app_contextPath + "/js/lib/backbone-min.js",
         app_contextPath + "/js/lib/date.format.js",           
         app_contextPath + "/js/util.js",
         app_contextPath + "/js/com/openclinica/renderer/RenderUtil.js",           
         app_contextPath + "/js/app.js",           
         app_contextPath + "/js/com/openclinica/renderer/ODMRenderer.js",           
         app_contextPath + "/js/com/openclinica/renderer/StudyDataLoader.js",           
         app_contextPath + "/js/com/openclinica/renderer/StudyRenderer.js",           
         app_contextPath + "/js/com/openclinica/renderer/FormDefRenderer.js",           
         app_contextPath + "/js/com/openclinica/renderer/StudyEventDefRenderer.js",           
         app_contextPath + "/js/com/openclinica/renderer/StudySubjectDefRenderer.js",           
         app_contextPath + "/js/com/openclinica/renderer/ItemDefRenderer.js",           
         app_contextPath + "/js/com/openclinica/renderer/PageHeaderRenderer.js",           
         app_contextPath + "/js/com/openclinica/renderer/ParseUtil.js"          
       );