  head.js(app_contextPath + "/js/lib/jquery-1.8.1.min.js", 
		   app_contextPath + "/js/lib/jquery-ui-1.8.23.custom.min.js",
           app_contextPath + "/js/lib/jquery.tmpl.js",
           app_contextPath + "/js/lib/underscore-min.js",           
           app_contextPath + "/js/lib/backbone-min.js",
           app_contextPath + "/js/lib/date.format.js",           
           app_contextPath + "/js/util.js",
           app_contextPath + "/js/app.js",           
           app_contextPath + "/js/com/openclinica/renderer/ODMRenderer.js",           
           app_contextPath + "/js/com/openclinica/renderer/StudyRenderer.js",           
           app_contextPath + "/js/com/openclinica/renderer/FormDefRenderer.js",           
           app_contextPath + "/js/com/openclinica/renderer/ItemDefRenderer.js",           
           app_contextPath + "/js/com/openclinica/renderer/PrintPageRenderer.js",           
           app_contextPath + "/js/com/openclinica/renderer/ParseUtil.js",           
           app_contextPath + "/js/com/openclinica/renderer/RenderUtil.js"           
         );