package org.akaza.openclinica;

public enum ParticipateInviteStatusEnum {
    EMAIL_INVITE_SUCCESS, SMS_INVITE_SUCCESS, BOTH_INVITE_FAIL,
    EMAIL_SUCCESS_SMS_FAIL, EMAIL_FAIL_SMS_SUCCESS,
    BOTH_INVITE_SUCCESS, EMAIL_INVITE_FAIL, SMS_INVITE_FAIL, NO_OP
}
