// default package
// Generated Jul 31, 2013 2:03:33 PM by Hibernate Tools 3.4.0.CR1
package org.akaza.openclinica.domain.datamap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.akaza.openclinica.domain.AbstractMutableDomainObject;

/**
 * AuditLogEventType generated by hbm2java
 */
@Entity
@Table(name = "audit_log_event_type", schema = "public")
public class AuditLogEventType extends AbstractMutableDomainObject {

	private int auditLogEventTypeId;
	private String name;

	public AuditLogEventType() {
	}

	public AuditLogEventType(int auditLogEventTypeId) {
		this.auditLogEventTypeId = auditLogEventTypeId;
	}

	public AuditLogEventType(int auditLogEventTypeId, String name) {
		this.auditLogEventTypeId = auditLogEventTypeId;
		this.name = name;
	}

	@Id
	@Column(name = "audit_log_event_type_id", unique = true, nullable = false)
	public int getAuditLogEventTypeId() {
		return this.auditLogEventTypeId;
	}

	public void setAuditLogEventTypeId(int auditLogEventTypeId) {
		this.auditLogEventTypeId = auditLogEventTypeId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
