

	// default package
	// Generated Jul 31, 2013 2:03:33 PM by Hibernate Tools 3.4.0.CR1
	package org.akaza.openclinica.domain.datamap;
	import java.util.Date;
	import java.util.List;

	import javax.persistence.CascadeType;
	import javax.persistence.Column;
	import javax.persistence.Entity;
	import javax.persistence.FetchType;
	import javax.persistence.GeneratedValue;
	import javax.persistence.Id;
	import javax.persistence.JoinColumn;
	import javax.persistence.ManyToOne;
	import javax.persistence.OneToMany;
	import javax.persistence.OrderBy;
	import javax.persistence.Table;
	import javax.persistence.Temporal;
	import javax.persistence.TemporalType;

	import org.akaza.openclinica.domain.DataMapDomainObject;
	import org.akaza.openclinica.domain.Status;
	import org.akaza.openclinica.domain.user.UserAccount;
	import org.hibernate.annotations.Cache;
	import org.hibernate.annotations.CacheConcurrencyStrategy;
	import org.hibernate.annotations.GenericGenerator;
	import org.hibernate.annotations.Parameter;
	import org.hibernate.annotations.Type;

	/**
	 * ItemData generated by hbm2java
	 */
	public class ItemDataBean  extends DataMapDomainObject {

		private int itemDataId;
		private UserAccount userAccount;
		private EventCrf eventCrf;
		private Item item;
		private Status status;
		private String value;
		private Date dateCreated;
		private Date dateUpdated;
		private Integer updateId;
		private Integer ordinal;
		private List<DnItemDataMap> dnItemDataMaps;

		public ItemDataBean() {
		}


		public int getItemDataId() {
			return this.itemDataId;
		}

		public void setItemDataId(int itemDataId) {
			this.itemDataId = itemDataId;
		}

		public UserAccount getUserAccount() {
			return this.userAccount;
		}

		public void setUserAccount(UserAccount userAccount) {
			this.userAccount = userAccount;
		}

		public EventCrf getEventCrf() {
			return this.eventCrf;
		}

		public void setEventCrf(EventCrf eventCrf) {
			this.eventCrf = eventCrf;
		}
		public Item getItem() {
			return this.item;
		}

		public void setItem(Item item) {
			this.item = item;
		}

	    public Status getStatus() {
	        if (status != null) {
	            return status;
	        } else
	            return Status.AVAILABLE;
	    }

		public void setStatus(Status status) {
			this.status = status;
		}

		public String getValue() {
			return this.value;
		}

		public void setValue(String value) {
			this.value = value;
		}

		public Date getDateCreated() {
			return this.dateCreated;
		}

		public void setDateCreated(Date dateCreated) {
			this.dateCreated = dateCreated;
		}

		public Date getDateUpdated() {
			return this.dateUpdated;
		}

		public void setDateUpdated(Date dateUpdated) {
			this.dateUpdated = dateUpdated;
		}

		public Integer getUpdateId() {
			return this.updateId;
		}

		public void setUpdateId(Integer updateId) {
			this.updateId = updateId;
		}

		public Integer getOrdinal() {
			return this.ordinal;
		}

		public void setOrdinal(Integer ordinal) {
			this.ordinal = ordinal;
		}

		
		public List<DnItemDataMap> getDnItemDataMaps() {
			return this.dnItemDataMaps;
		}

		public void setDnItemDataMaps(List<DnItemDataMap> dnItemDataMaps) {
			this.dnItemDataMaps = dnItemDataMaps;
		}




	
}
