package org.akaza.openclinica.domain.datamap;
// Generated Jul 31, 2013 2:03:33 PM by Hibernate Tools 3.4.0.CR1

import org.akaza.openclinica.domain.CompositeIdDomainObject;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;
import java.util.Date;

/**
 * StudyUserRole generated by hbm2java
 */
@Entity @Table(name = "study_user_role") @Cache(usage = CacheConcurrencyStrategy.READ_WRITE) public class StudyUserRole implements CompositeIdDomainObject {
    private Date dateCreated;
    private Date dateUpdated;
    private Integer statusId;
    private Integer updateId;
    private Integer ownerId;
    private StudyUserRoleId id;
    private String roleName;


    public StudyUserRole() {
    }

    public StudyUserRole(StudyUserRoleId id) {
        this.id = id;
    }

    @Column(name = "role_name", length = 40)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "date_created") public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Column(name = "date_updated")

    public Date getDateUpdated() {
        return dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    @Column(name = "status_id") public Integer getStatusId() {
        return statusId;
    }

    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    @Column(name = "update_id") public Integer getUpdateId() {
        return updateId;
    }

    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    @Column(name = "owner_id") public Integer getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    @EmbeddedId @AttributeOverrides({ @AttributeOverride(name = "roleName", column = @Column(name = "role_name", length = 40)),
            @AttributeOverride(name = "studyId", column = @Column(name = "study_id")),
            @AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 40)), }) public StudyUserRoleId getId() {
        return this.id;
    }

    public void setId(Object id) {
        this.id = (StudyUserRoleId) id;
    }

    public void setId(StudyUserRoleId id) {
        this.id = id;
    }

}