package org.akaza.openclinica.domain.datamap;
// Generated Jul 31, 2013 2:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.akaza.openclinica.domain.AbstractMutableDomainObject;
import org.akaza.openclinica.domain.DataMapDomainObject;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * StudyType generated by hbm2java
 */
@Entity
@Table(name = "study_type")
public class StudyType  extends DataMapDomainObject {

	private int studyTypeId;
	private String name;
	private String description;
	private Set studies = new HashSet(0);

	public StudyType() {
	}

	public StudyType(int studyTypeId) {
		this.studyTypeId = studyTypeId;
	}

	public StudyType(int studyTypeId, String name, String description,
			Set studies) {
		this.studyTypeId = studyTypeId;
		this.name = name;
		this.description = description;
		this.studies = studies;
	}

	@Id
	@Column(name = "study_type_id", unique = true, nullable = false)
	public int getStudyTypeId() {
		return this.studyTypeId;
	}

	public void setStudyTypeId(int studyTypeId) {
		this.studyTypeId = studyTypeId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studyType")
	public Set getStudies() {
		return this.studies;
	}

	public void setStudies(Set studies) {
		this.studies = studies;
	}

}
