package org.akaza.openclinica.domain.datamap;
//default package

//Generated Jul 31, 2013 2:03:33 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.akaza.openclinica.domain.DataMapDomainObject;

/**
 * VersioningMapId generated by hbm2java
 */
@Embeddable
public class VersioningMapId extends DataMapDomainObject {

    private Integer crfVersionId;
    private Integer itemId;
    private Integer formLayoutId;
    private Integer itemOrderInForm;

    public VersioningMapId() {
    }

    public VersioningMapId(Integer crfVersionId, Integer itemId,Integer formLayoutId, Integer itemOrderInForm) {
        this.crfVersionId = crfVersionId;
        this.itemId = itemId;
        this.formLayoutId=formLayoutId;
        this.itemOrderInForm=itemOrderInForm;
    }

    @Column(name = "crf_version_id")
    public Integer getCrfVersionId() {
        return this.crfVersionId;
    }

    public void setCrfVersionId(Integer crfVersionId) {
        this.crfVersionId = crfVersionId;
    }

    @Column(name = "item_id")
    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    @Column(name = "form_layout_id")
    public Integer getFormLayoutId() {
        return formLayoutId;
    }

    public void setFormLayoutId(Integer formLayoutId) {
        this.formLayoutId = formLayoutId;
    }

    @Column(name = "item_order_in_form")
    public Integer getItemOrderInForm() {
        return itemOrderInForm;
    }

    public void setItemOrderInForm(Integer itemOrderInForm) {
        this.itemOrderInForm = itemOrderInForm;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof VersioningMapId))
            return false;
        VersioningMapId castOther = (VersioningMapId) other;

        return ((this.getCrfVersionId() == castOther.getCrfVersionId())
                || (this.getCrfVersionId() != null && castOther.getCrfVersionId() != null && this.getCrfVersionId().equals(castOther.getCrfVersionId())))
                && ((this.getItemId() == castOther.getItemId())
                        || (this.getItemId() != null && castOther.getItemId() != null && this.getItemId().equals(castOther.getItemId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getCrfVersionId() == null ? 0 : this.getCrfVersionId().hashCode());
        result = 37 * result + (getItemId() == null ? 0 : this.getItemId().hashCode());
        return result;
    }

}
